In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)          # one-dimensional array
x2 = np.random.randint(10, size=(3, 4))     # two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # three-dimensional array

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [3]:
print("dtype; ", x3.dtype)

dtype;  int64


In [4]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


In [5]:
x3.nbytes // x3.itemsize

60

In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[4]

7

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[0, 0]

3

In [13]:
x2[2, 0]

1

In [14]:
x2[2, -1]

7

In [15]:
x2[0, 0] = 12

In [16]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [17]:
x1[0] = 3.14159  # this will be truncated!

x1

# Slicing
## One-dimensional subarrays

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [20]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [21]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [22]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [23]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [24]:
x[::-1]  # all elements, reversed (swapped)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

# Slicing
## Multi-dimensional subarrays

In [26]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [27]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [28]:
x2[:3, ::2]  # all rows, everty other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [29]:
x2 [::-1, ::-1]  # reversing all subarrays

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Accessing array rows and columns

In [30]:
print(x2[:, 0])  # first row of x2

[12  7  1]


In [31]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [32]:
print(x2[0])  # first row without slicing notation (equivalent to x2[0, :])

[12  5  2  4]


## Subarrays as no-copy views

Slicing notation returns a "view" of an array rather than copies of the arrays data

In [33]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


##### Let's extract a 2x2 subarray from this:

In [34]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


##### if we modify this subarray, the original array will be changed

In [35]:
x2_sub[0, 0] = 99
print(x2_sub)
print("=" * 20)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Creating copies of arrays

In [36]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [37]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [38]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Reshaping of arrays

In [39]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
x = np.array([1, 2, 3])

In [41]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [42]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [43]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [44]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenation of arrays

In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [47]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [48]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
# Concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [51]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting og arrays

In [52]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [53]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [55]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
